repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: double-quote-string-fixer
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/best-doctor/pre-commit-hooks
    rev: v1.0.11
    hooks:
    - id: mccabe-complexity
      name: Check functions complexity
      language: python
    - id: line-count
      name: Check number of lines in python files
      language: python


  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black

  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort
      language: system
      pass_filenames: false

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
    - id: absolufy-imports

  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.2
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      pass_filenames: false
      args:
        - excelalchemy

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    - id: reorder-python-imports
      name: Reorder imports
      pass_filenames: false

  - repo: local
    hooks:
    - id: pyright
      name: pyright
      entry: pyright
      language: system
      pass_filenames: false
      args:
        - excelalchemy

  - repo: local
    hooks:
      - id: mypy-excelalchemy
        name: mypy-excelalchemy
        entry: mypy
        args:
          - excelalchemy
        pass_filenames: false
        language: system
